In [2]:
import requests
import json

# Define the API endpoint URL
api_url = "https://nileva.meta-bytes.net/api/products"

# Make GET request to the endpoint
response = requests.get(api_url)

# Check if request was successful
if response.status_code == 200:
    # Parse JSON response
    products_data = response.json()
    
    # Save data to file for later use
    with open('products.json', 'w') as f:
        json.dump(products_data, f, indent=4)
        
    print(f"Successfully retrieved {len(products_data)} products")
    print("Data saved to products.json")
else:
    print(f"Failed to get data: {response.status_code}")
    print(response.text)

Successfully retrieved 3 products
Data saved to products.json

In [3]:
with open(r'..\Dataset\products.json', 'r') as f:
    response = json.load(f)

response

{'event_type': 'products.updated',
 'timestamp': '2025-04-17T15:39:22.403774Z',
 'data': {'products': [{'product_id': 1,
    'name': 'Herforte Lotion Spray (to fill in gaps and treat alopecia)',
    'description': 'Hair forte is a mixture of natural extracts and extracts of the most important hair oils with anti-dandruff agent, to be a quick treatment for hair loss, guaranteed and tested by dermatologists for fortifying hair & increase hair shaft strength to prevent hair loss. Also, Hair forte spray stimulates hair germination to be an effective solution to fill the frontal spaces in women and men, in addition to treating dandruff & itching associated with dryness and inflammation of the scalp, Hair forte spray is suitable for all hair types even oily & dry scalp.\r\n\r\nComposition:-\r\nHair forte spray with its unique formula to be effective in stimulating the blood circulation of the scalp and hair follicles to strengthen and nourish them to prevent hair loss and also to stimulate root germination for the growth of healthy, thick, long and strong hair without dandruff.\r\n\r\n•\tJojoba Oil Extract.\r\n•\tGarlic Oil Extract.\r\n•\tNigella.\r\n•\tRosemary.\r\n•\tCaffeine.\r\n•\tThyme Oil.\r\n•\tSalicylic acid.\r\n•\tPanthenol.\r\n•\tAloe Vera.\r\n•\tVitamin E.\r\nIndicated for:\r\n*Diffuse hair fall.\r\n*Adjuvant therapy for alopecia areata. \r\n*Controls split ends, roughness, dryness& brittleness of hair. \r\n*Controls dandruff.\r\n\r\nApplication:\r\nSpray onto wet or dry hair& scalp “6 pump” suitable amount then massage& style as usual, once or twice daily preferably start from the forehead to back of the head in a circular movement or as directed by physician.\r\n\r\nPackage:\r\n 120 ml.',
    'ingredients': ['Jojoba Oil Extract',
     'Garlic Oil Extract',
     'Nigella',
     'Rosemary',
     'Caffeine',
     'Thyme Oil',
     'Salicylic acid',
     'Panthenol',
     'Aloe Vera',
     'Vitamin E'],
    'concerns': [['Hair loss']],
    'category': ['Hair Care', 'Hair spray& lotion'],
    'price': '200.00',
    'product_file': None,
    'best_seller': True,
    'new_arrived': False},
   {'product_id': 2,
    'name': 'Hairforte Shampoo (for treating hair loss and dandruff + deep moisturizing)',
    'description': 'Hair Forte shampoo is an effective combination of anti-dandruff with natural extracts& important oils for hair to get rid of dandruff while nourishing &moisturizing hair to reduce hair falling also it helps in stimulating hair growth, Hair forte shampoo For Both Treated hair and Normal one.\r\n\r\nComposition:\r\n\r\n•\tCaffeine.\r\n•\tJojoba Oil.\r\n•\tLavender Oil.\r\n•\tCoconut Oil.\r\n•\tOlive Oil.\r\n•\tRosemary Oil.\r\n•\tVitamin E.\r\n•\tPanthenol.\r\n•\tAloe Vera.\r\n•\tZinc Pyrithione.\r\n•\tGarlic Extract.\r\n•\tTriclosan.\r\nIndicated for:\r\n\r\n*Treatment of dandruff.\r\n*Diffuse hair fall.\r\n*Adjuvant therapy for alopecia areata. \r\n*Controls split ends, roughness, dryness& brittleness of hair.\r\n\r\n\r\nApplication:\r\nApply a sufficient amount on wet hair and scalp, with gentle massage then rinse well with water from 1: 2 times weekly.\r\nPackage:\r\n 120 ml.',
    'ingredients': ['Caffeine',
     'Jojoba Oil',
     'Lavender Oil',
     'Coconut Oil',
     'Olive Oil',
     'Rosemary Oil',
     'Vitamin E',
     'Panthenol',
     'Aloe Vera',
     'Zinc Pyrithione',
     'Garlic Extract',
     'Triclosan'],
    'concerns': [['Dandruff']],
    'category': ['Hair Care', 'Shampoos'],
    'price': '150.00',
    'product_file': None,
    'best_seller': True,
    'new_arrived': False},
   {'product_id': 3,
    'name': 'Valdo moisturizing cream',
    'description': 'Valdo Moisturizing Cream\r\n-The best moisturizing cream for the face - hands - body and sensitive areas -\r\n -Valdo treats severe dryness and rebuilds the skin barrier.\r\n- Makes the skin soft and hydrated all day without scales\r\n-Valdo cream is rich in anti-inflammatory and antibacterial.\r\n -To treat skin infections and dissections also sunburn and burns first degree -\r\n-Accelerates wound healing. It is worth noting that its composition Valdo cream is rich in antioxidants.\r\n  - Collagen stimulator to provide freshness and get rid of pallor and dullness.\r\n - Protection against the appearance of premature wrinkles\r\n- For all skin types (for dry skin - for oily skin - for combination and normal skin)\r\n\r\nComposition:\r\nValdo cream is an ideal natural mix from most important natural extracts, oils& vitamins for complete skin care\r\n•\tPanthenol “Vitamin B5”.\r\n•\tAloe Vera.\r\n•\tCalendula.\r\n•\tAlmond Oil.\r\n•\tOlive Oil.\r\n•\tAllantoin..\r\n•\tGlycerin.\r\n•\tVitamin E.\r\n•\tVitamin C.\r\n•\tDimethicone.\r\nIndicated for:\r\n•\tEczema.\r\n•\tDry Skin.\r\n•\tSun burn.\r\n•\tBurn “1st” degree.\r\n•\tDipper rash.\r\n•\tNipple Fissure.\r\n•\tPost Laser care.\r\n•\tAfter care of derma pen.\r\n•\tReduce the early appearance of wrinkle.\r\n•\tDaily skin routine for glowing& taut look.\r\n•\tAdjuvant Therapy in Acne Vulgaris. \r\n\r\nApplication:-\r\nApply a suitable amount of the Valdo cream to skin twice daily.\r\nPackage:\r\n  40gm.',
    'ingredients': ['Panthenol (Vitamin B5)',
     'Aloe Vera',
     'Calendula',
     'Almond Oil',
     'Olive Oil',
     'Allantoin',
     'Glycerin',
     'Vitamin E',
     'Vitamin C',
     'Dimethicone'],
    'concerns': [['Eczema & Dry skin']],
    'category': ['Skin Care', 'Moisturizer'],
    'price': '80.00',
    'product_file': None,
    'best_seller': True,
    'new_arrived': False},
   {'product_id': 4,
    'name': 'Spleet Cream Scrub (Steam Alternative + Acne Treatment)',
    'description': 'Spleet is a gentle exfoliating cream with a unique triple action therapeutic formula for treating active acne, hidden pimple and dark spots, Spleet exfoliating has a soft peeling effect to remove dead skin buildup extremely dry, rough, scaly and aging skin Plus promoting a deep hydration that makes skin soft, smooth and less flaking. Spleet cream is safe for Face, hand, foot& full body and suitable for all kind of skin.\r\n\r\n\r\nComposition:- \r\nSpleet is an effective combination of the following:- \r\n•\t Urea \r\n•\tSalicylic Acid \r\n•\tLactic Acid\r\n•\tTea Tree Oil.\r\n•\tChamomile.\r\nIndicated for:\r\n•\tSevere dry Skin.\r\n•\tKeratosis pilaris.\r\n•\tCracked heel.\r\n•\tRough, discolored elbow & knee.\r\n•\tPsoriasis patches. \r\n•\tEczema.\r\n•\tActive acne.\r\n•\tHidden pimple\r\n•\tDark spots\r\n•\tHydrate, brighten& smooth fine lines.\r\nApplication:-\r\nApply a suitable amount of the cream to skin once daily.\r\nFor sensitive skin just applied for 5 minute then washed.\r\nPackage:\r\n 40gm.',
    'ingredients': ['Urea',
     'Salicylic Acid',
     'Lactic Acid',
     'Tea Tree Oil',
     'Chamomile'],
    'concerns': [['Strawberry skin treatment',
      'Acne& acne spots',
      'Hyperpigmentation& dark spots',
      'Sensitive areas& Bikini area brightening',
      'Dull& pale skin']],
    'category': ['Personal Care', 'Soft peel and Exfoliant'],
    'price': '100.00',
    'product_file': None,
    'best_seller': True,
    'new_arrived': False},
   {'product_id': 5,
    'name': 'Spleet Lightening Cream (for treating pigmentation and acne scars)',
    'description': 'Spleet whitening cream offers the strongest unique natural formula that works through triple powers of lighten- moisturize& skin rejuvenation with triple different mechanisms of action for Achieving a de-pigmentation effect to lighten dark spots effectively & unify the skin tone hinder the development of dark patches and  Keep skin hydrated& protected, it  also  stimulates collagen production and regulate sebum secretion to reduce the appearance of acne, pimple and large pores, Spleet whitening cream is sfor face, sensitive areas, under arm, bikini& full body and for All skin types “ dry skin - normal - mixed - oily or sensitive skin" either for girls, women or  men, Spleet whitening cream.\r\n\r\n\r\nComposition: \r\nSpleet whitening cream is a potent composition from triple groups of ingredients “skin lightening agents, skin exfoliating agents and skin moisturizing& antioxidant agents for treatment of hyperpigmentation and lighten dark spots effectively leaving skin hydrated and renewed.\r\n\r\n•\tAlpha- Arbutin, \r\n•\tKojic Acid. \r\n•\tNiacinamide. \r\n•\tLicorice. \r\n•\tGlycolic Acid. \r\n•\tVitamin A.\r\n•\tVitamin C.\r\n•\tVitamin E\r\n•\tZinc oxid.\r\n•\t Allantoin.\r\n•\tGlycerin.\r\nIndicated for:\r\no\tSun Exposure. \r\no\tAge Spots                     \r\no\tMelasma.\r\no\tPost Inflammatory hyperpigmentation as:\r\n•\tAcne scars.\r\n•\tSunburn.                \r\n•\tAfter care of chemical peels.            \r\n•\tPost laser resurfacing.\r\n\r\n\r\nApplications:\r\nApply a small amount on the face or area to be lightened once at night and may be repeated when needed.\r\nPackage:\r\n 40gm.',
    'ingredients': ['Alpha-Arbutin',
     'Kojic Acid',
     'Niacinamide',
     'Licorice',
     'Glycolic Acid',
     'Vitamin A',
     'Vitamin C',
     'Vitamin E',
     'Zinc Oxide',
     'Allantoin',
     'Glycerin'],
    'concerns': [['Hyperpigmentation& dark spots',
      'Sensitive areas& Bikini area brightening',
      'Acne& acne spots']],
    'category': ['Skin Care', 'Whitening cream'],
    'price': '100.00',
    'product_file': None,
    'best_seller': True,
    'new_arrived': False},
   {'product_id': 6,
    'name': 'Spleet Eye Contour Cream (for treating dark circles + expression lines + deep moisturizing)',
    'description': 'An unique  potent  mix of natural  ingredients those act with three functions “hydrate- brighten- firm” effectively addresses every single eye area concern- leaving the eye more brighter and smoother, that suitable for all kind of skin even sensitive skin. \r\n1- Truly nourish the skin with multiple nutrients & vitamin as vitamin E& K and stimulating blood circulation plus deeply moisturize skin around the eyes for brightening skin, reducing the dark circles without clogging the pores.\r\n  2- Improving skin hydration and elasticity the eye contour area deeply plus antioxidant effect that will help in reliving of puffiness& eye fatigue.\r\n3- Help in reducing the appearance of fine lines through promoting skin renewal and improving skin elasticity by stimulating of the collagen synthesis\r\nComposition: \r\n*Caffeine.\r\n*Liquorice Extract.  \r\n*Vitamin A.\r\n*Green Tea.\r\n *Almond Oil.\r\n *Wheat Germ Oil.\r\n *Chamomile Extract.\r\n*Allantoin.\r\n*Royal Jelly.\r\n*Panthenol.  \r\n*Collagen.\r\n\r\nIndicated for:\r\n•\tTreatment of all types of dark circles: \r\nBrown dark Circle due to hyperpigmentation “by Licorice” \r\nBlack dark Circle due to lack of collagen and elasticity “by royal, panthenol & collagen”\r\nBlue dark Circle due to bad circulation “with caffeine& natural vitamin K extract”.\r\n•\tMoisturizes and strengthens the skin texture around the eyes. \r\n•\tReduce the transparency of the tissues around the eye to reduce the appearance of dark circles. \r\n•\tEye bag or puffiness.\r\n\r\n•\tEraser of fine lines.\r\n•\tRelieve of eye fatigue.\r\n\r\nApplication: \r\nApply a small amount with gentle smoothing under the eye area, can be used alone or under makeup.\r\n\r\nPackage:\r\n30 gm.',
    'ingredients': ['Caffeine',
     'Liquorice Extract',
     'Vitamin A',
     'Green Tea',
     'Almond Oil',
     'Wheat Germ Oil',
     'Chamomile Extract',
     'Allantoin',
     'Royal Jelly',
     'Panthenol',
     'Collagen'],
    'concerns': [['Hyperpigmentation& dark spots',
      'Dark circles “blue- brown- black” & puffiness']],
    'category': ['Skin Care', 'Eye cream'],
    'price': '225.00',
    'product_file': None,
    'best_seller': True,
    'new_arrived': False},
   {'product_id': 7,
    'name': 'Spleet Facial wash',
    'description': 'Spleet face wash with an unique the Canadian balanced formula that keeps skin pH balanced to be safe and  suitable for all skin types that work with 5 power to give marvels 5  effects and effectiveness to show the beauty of the skin naturally and safely, as it helps to clean the skin for getting rid  of accumulated makeup and debris to gives it a sense of freshness with an effect in lightening and enlightening the skin significantly, also helps it get rid of acne, pimples and reduce the appearance of enlarged pores and give  a tightening of the skin because it is rich in collagen stimuli plus natural collagen with important vitamins those rejuvenate and tighten the skin to help it fight the appearance of early wrinkles leaving the skin deeply moisturized along the day.\r\nComposition: \r\n•\tAloe Vera Extract.\r\n•\tJojoba Oil.\r\n•\tTocopherol.\r\n•\tCollagen.\r\n•\tCamellia Sinensis Extract.\r\n•\tGlycyrrhiza Glabra Leaf Extract.\r\n•\tSalicylic Acid.\r\n•\tGlycolic Acid.\r\n•\tGlycerin.\r\n•\tGlycine.\r\n\r\nIndicated for:\r\n\r\n• It cleans the skin effectively and safely.\r\n• Lighten skin color.\r\n• Moisturizing the skin deeply.\r\n• Treating Acne and pimples.\r\n• Rejuvenation and tightening of the skin.\r\n•\tReduce the appearance of enlarged pores\r\n• Suitable for daily use.\r\n• A very small amount is sufficient.\r\n• Easy to rinse off.\r\n• Reduces fatty secretions.\r\n• Light and distinct scent.\r\n• Free of soap and does not cause clogged pores.\r\n\r\nApplication: \r\nApply a small amount on the face with a little of water, gently massage and then rinse, twice daily.\r\n\r\nPackage:\r\n200 ml.',
    'ingredients': ['Aloe Vera Extract',
     'Jojoba Oil',
     'Tocopherol',
     'Collagen',
     'Camellia Sinensis Extract',
     'Glycyrrhiza Glabra Leaf Extract',
     'Salicylic Acid',
     'Glycolic Acid',
     'Glycerin',
     'Glycine'],
    'concerns': [['Acne& acne spots',
      'Hyperpigmentation& dark spots',
      'Dull& pale skin',
      'Eczema & Dry skin']],
    'category': ['Skin Care', 'Cleansers'],
    'price': '220.00',
    'product_file': None,
    'best_seller': True,
    'new_arrived': False},
   {'product_id': 12,
    'name': 'Aceto-V Feminine Intimate wash',
    'description': 'Acet-V is a feminine Intimate wash with unique combination of real treatment for vaginal infection either bacterial or fungal plus moisturizers, tightening agents to enjoy daily activities& sexual intercourse. \r\nComposition:- \r\n*Chlorhexidine gluconate.\r\n *Cetrimide. \r\n*Aloe Vera.\r\n*Chamomile.\r\n*Glycerin.\r\n\r\nIndicated for:\r\n•\tBacterial vaginosis. \r\n•\tVaginal candidiasis.\r\n•\tAtrophic Vaginitis.\r\n•\tVaginal irritation& itching. \r\n•\tPersonal hygiene during menstrual cycle.\r\n•\tPersonal hygiene after sexual intercourse.\r\n•\tPersonal hygiene after Labor.\r\n•\tTighten the vagina.\r\nApplication:-\r\nApplied directly without dilution, once per day for external use only.\r\n\r\nPackage:\r\n250ml.',
    'ingredients': ['Chlorhexidine gluconate',
     'Cetrimide',
     'Aloe Vera',
     'Chamomile',
     'Glycerin'],
    'concerns': [['Sensitive areas& Bikini area brightening']],
    'category': ['Personal Care', 'Cleansers'],
    'price': '90.00',
    'product_file': None,
    'best_seller': False,
    'new_arrived': False}]}}

In [4]:
import pandas as pd

In [5]:
response['data']['products']

[{'product_id': 1,
  'name': 'Herforte Lotion Spray (to fill in gaps and treat alopecia)',
  'description': 'Hair forte is a mixture of natural extracts and extracts of the most important hair oils with anti-dandruff agent, to be a quick treatment for hair loss, guaranteed and tested by dermatologists for fortifying hair & increase hair shaft strength to prevent hair loss. Also, Hair forte spray stimulates hair germination to be an effective solution to fill the frontal spaces in women and men, in addition to treating dandruff & itching associated with dryness and inflammation of the scalp, Hair forte spray is suitable for all hair types even oily & dry scalp.\r\n\r\nComposition:-\r\nHair forte spray with its unique formula to be effective in stimulating the blood circulation of the scalp and hair follicles to strengthen and nourish them to prevent hair loss and also to stimulate root germination for the growth of healthy, thick, long and strong hair without dandruff.\r\n\r\n•\tJojoba Oil Extract.\r\n•\tGarlic Oil Extract.\r\n•\tNigella.\r\n•\tRosemary.\r\n•\tCaffeine.\r\n•\tThyme Oil.\r\n•\tSalicylic acid.\r\n•\tPanthenol.\r\n•\tAloe Vera.\r\n•\tVitamin E.\r\nIndicated for:\r\n*Diffuse hair fall.\r\n*Adjuvant therapy for alopecia areata. \r\n*Controls split ends, roughness, dryness& brittleness of hair. \r\n*Controls dandruff.\r\n\r\nApplication:\r\nSpray onto wet or dry hair& scalp “6 pump” suitable amount then massage& style as usual, once or twice daily preferably start from the forehead to back of the head in a circular movement or as directed by physician.\r\n\r\nPackage:\r\n 120 ml.',
  'ingredients': ['Jojoba Oil Extract',
   'Garlic Oil Extract',
   'Nigella',
   'Rosemary',
   'Caffeine',
   'Thyme Oil',
   'Salicylic acid',
   'Panthenol',
   'Aloe Vera',
   'Vitamin E'],
  'concerns': [['Hair loss']],
  'category': ['Hair Care', 'Hair spray& lotion'],
  'price': '200.00',
  'product_file': None,
  'best_seller': True,
  'new_arrived': False},
 {'product_id': 2,
  'name': 'Hairforte Shampoo (for treating hair loss and dandruff + deep moisturizing)',
  'description': 'Hair Forte shampoo is an effective combination of anti-dandruff with natural extracts& important oils for hair to get rid of dandruff while nourishing &moisturizing hair to reduce hair falling also it helps in stimulating hair growth, Hair forte shampoo For Both Treated hair and Normal one.\r\n\r\nComposition:\r\n\r\n•\tCaffeine.\r\n•\tJojoba Oil.\r\n•\tLavender Oil.\r\n•\tCoconut Oil.\r\n•\tOlive Oil.\r\n•\tRosemary Oil.\r\n•\tVitamin E.\r\n•\tPanthenol.\r\n•\tAloe Vera.\r\n•\tZinc Pyrithione.\r\n•\tGarlic Extract.\r\n•\tTriclosan.\r\nIndicated for:\r\n\r\n*Treatment of dandruff.\r\n*Diffuse hair fall.\r\n*Adjuvant therapy for alopecia areata. \r\n*Controls split ends, roughness, dryness& brittleness of hair.\r\n\r\n\r\nApplication:\r\nApply a sufficient amount on wet hair and scalp, with gentle massage then rinse well with water from 1: 2 times weekly.\r\nPackage:\r\n 120 ml.',
  'ingredients': ['Caffeine',
   'Jojoba Oil',
   'Lavender Oil',
   'Coconut Oil',
   'Olive Oil',
   'Rosemary Oil',
   'Vitamin E',
   'Panthenol',
   'Aloe Vera',
   'Zinc Pyrithione',
   'Garlic Extract',
   'Triclosan'],
  'concerns': [['Dandruff']],
  'category': ['Hair Care', 'Shampoos'],
  'price': '150.00',
  'product_file': None,
  'best_seller': True,
  'new_arrived': False},
 {'product_id': 3,
  'name': 'Valdo moisturizing cream',
  'description': 'Valdo Moisturizing Cream\r\n-The best moisturizing cream for the face - hands - body and sensitive areas -\r\n -Valdo treats severe dryness and rebuilds the skin barrier.\r\n- Makes the skin soft and hydrated all day without scales\r\n-Valdo cream is rich in anti-inflammatory and antibacterial.\r\n -To treat skin infections and dissections also sunburn and burns first degree -\r\n-Accelerates wound healing. It is worth noting that its composition Valdo cream is rich in antioxidants.\r\n  - Collagen stimulator to provide freshness and get rid of pallor and dullness.\r\n - Protection against the appearance of premature wrinkles\r\n- For all skin types (for dry skin - for oily skin - for combination and normal skin)\r\n\r\nComposition:\r\nValdo cream is an ideal natural mix from most important natural extracts, oils& vitamins for complete skin care\r\n•\tPanthenol “Vitamin B5”.\r\n•\tAloe Vera.\r\n•\tCalendula.\r\n•\tAlmond Oil.\r\n•\tOlive Oil.\r\n•\tAllantoin..\r\n•\tGlycerin.\r\n•\tVitamin E.\r\n•\tVitamin C.\r\n•\tDimethicone.\r\nIndicated for:\r\n•\tEczema.\r\n•\tDry Skin.\r\n•\tSun burn.\r\n•\tBurn “1st” degree.\r\n•\tDipper rash.\r\n•\tNipple Fissure.\r\n•\tPost Laser care.\r\n•\tAfter care of derma pen.\r\n•\tReduce the early appearance of wrinkle.\r\n•\tDaily skin routine for glowing& taut look.\r\n•\tAdjuvant Therapy in Acne Vulgaris. \r\n\r\nApplication:-\r\nApply a suitable amount of the Valdo cream to skin twice daily.\r\nPackage:\r\n  40gm.',
  'ingredients': ['Panthenol (Vitamin B5)',
   'Aloe Vera',
   'Calendula',
   'Almond Oil',
   'Olive Oil',
   'Allantoin',
   'Glycerin',
   'Vitamin E',
   'Vitamin C',
   'Dimethicone'],
  'concerns': [['Eczema & Dry skin']],
  'category': ['Skin Care', 'Moisturizer'],
  'price': '80.00',
  'product_file': None,
  'best_seller': True,
  'new_arrived': False},
 {'product_id': 4,
  'name': 'Spleet Cream Scrub (Steam Alternative + Acne Treatment)',
  'description': 'Spleet is a gentle exfoliating cream with a unique triple action therapeutic formula for treating active acne, hidden pimple and dark spots, Spleet exfoliating has a soft peeling effect to remove dead skin buildup extremely dry, rough, scaly and aging skin Plus promoting a deep hydration that makes skin soft, smooth and less flaking. Spleet cream is safe for Face, hand, foot& full body and suitable for all kind of skin.\r\n\r\n\r\nComposition:- \r\nSpleet is an effective combination of the following:- \r\n•\t Urea \r\n•\tSalicylic Acid \r\n•\tLactic Acid\r\n•\tTea Tree Oil.\r\n•\tChamomile.\r\nIndicated for:\r\n•\tSevere dry Skin.\r\n•\tKeratosis pilaris.\r\n•\tCracked heel.\r\n•\tRough, discolored elbow & knee.\r\n•\tPsoriasis patches. \r\n•\tEczema.\r\n•\tActive acne.\r\n•\tHidden pimple\r\n•\tDark spots\r\n•\tHydrate, brighten& smooth fine lines.\r\nApplication:-\r\nApply a suitable amount of the cream to skin once daily.\r\nFor sensitive skin just applied for 5 minute then washed.\r\nPackage:\r\n 40gm.',
  'ingredients': ['Urea',
   'Salicylic Acid',
   'Lactic Acid',
   'Tea Tree Oil',
   'Chamomile'],
  'concerns': [['Strawberry skin treatment',
    'Acne& acne spots',
    'Hyperpigmentation& dark spots',
    'Sensitive areas& Bikini area brightening',
    'Dull& pale skin']],
  'category': ['Personal Care', 'Soft peel and Exfoliant'],
  'price': '100.00',
  'product_file': None,
  'best_seller': True,
  'new_arrived': False},
 {'product_id': 5,
  'name': 'Spleet Lightening Cream (for treating pigmentation and acne scars)',
  'description': 'Spleet whitening cream offers the strongest unique natural formula that works through triple powers of lighten- moisturize& skin rejuvenation with triple different mechanisms of action for Achieving a de-pigmentation effect to lighten dark spots effectively & unify the skin tone hinder the development of dark patches and  Keep skin hydrated& protected, it  also  stimulates collagen production and regulate sebum secretion to reduce the appearance of acne, pimple and large pores, Spleet whitening cream is sfor face, sensitive areas, under arm, bikini& full body and for All skin types “ dry skin - normal - mixed - oily or sensitive skin" either for girls, women or  men, Spleet whitening cream.\r\n\r\n\r\nComposition: \r\nSpleet whitening cream is a potent composition from triple groups of ingredients “skin lightening agents, skin exfoliating agents and skin moisturizing& antioxidant agents for treatment of hyperpigmentation and lighten dark spots effectively leaving skin hydrated and renewed.\r\n\r\n•\tAlpha- Arbutin, \r\n•\tKojic Acid. \r\n•\tNiacinamide. \r\n•\tLicorice. \r\n•\tGlycolic Acid. \r\n•\tVitamin A.\r\n•\tVitamin C.\r\n•\tVitamin E\r\n•\tZinc oxid.\r\n•\t Allantoin.\r\n•\tGlycerin.\r\nIndicated for:\r\no\tSun Exposure. \r\no\tAge Spots                     \r\no\tMelasma.\r\no\tPost Inflammatory hyperpigmentation as:\r\n•\tAcne scars.\r\n•\tSunburn.                \r\n•\tAfter care of chemical peels.            \r\n•\tPost laser resurfacing.\r\n\r\n\r\nApplications:\r\nApply a small amount on the face or area to be lightened once at night and may be repeated when needed.\r\nPackage:\r\n 40gm.',
  'ingredients': ['Alpha-Arbutin',
   'Kojic Acid',
   'Niacinamide',
   'Licorice',
   'Glycolic Acid',
   'Vitamin A',
   'Vitamin C',
   'Vitamin E',
   'Zinc Oxide',
   'Allantoin',
   'Glycerin'],
  'concerns': [['Hyperpigmentation& dark spots',
    'Sensitive areas& Bikini area brightening',
    'Acne& acne spots']],
  'category': ['Skin Care', 'Whitening cream'],
  'price': '100.00',
  'product_file': None,
  'best_seller': True,
  'new_arrived': False},
 {'product_id': 6,
  'name': 'Spleet Eye Contour Cream (for treating dark circles + expression lines + deep moisturizing)',
  'description': 'An unique  potent  mix of natural  ingredients those act with three functions “hydrate- brighten- firm” effectively addresses every single eye area concern- leaving the eye more brighter and smoother, that suitable for all kind of skin even sensitive skin. \r\n1- Truly nourish the skin with multiple nutrients & vitamin as vitamin E& K and stimulating blood circulation plus deeply moisturize skin around the eyes for brightening skin, reducing the dark circles without clogging the pores.\r\n  2- Improving skin hydration and elasticity the eye contour area deeply plus antioxidant effect that will help in reliving of puffiness& eye fatigue.\r\n3- Help in reducing the appearance of fine lines through promoting skin renewal and improving skin elasticity by stimulating of the collagen synthesis\r\nComposition: \r\n*Caffeine.\r\n*Liquorice Extract.  \r\n*Vitamin A.\r\n*Green Tea.\r\n *Almond Oil.\r\n *Wheat Germ Oil.\r\n *Chamomile Extract.\r\n*Allantoin.\r\n*Royal Jelly.\r\n*Panthenol.  \r\n*Collagen.\r\n\r\nIndicated for:\r\n•\tTreatment of all types of dark circles: \r\nBrown dark Circle due to hyperpigmentation “by Licorice” \r\nBlack dark Circle due to lack of collagen and elasticity “by royal, panthenol & collagen”\r\nBlue dark Circle due to bad circulation “with caffeine& natural vitamin K extract”.\r\n•\tMoisturizes and strengthens the skin texture around the eyes. \r\n•\tReduce the transparency of the tissues around the eye to reduce the appearance of dark circles. \r\n•\tEye bag or puffiness.\r\n\r\n•\tEraser of fine lines.\r\n•\tRelieve of eye fatigue.\r\n\r\nApplication: \r\nApply a small amount with gentle smoothing under the eye area, can be used alone or under makeup.\r\n\r\nPackage:\r\n30 gm.',
  'ingredients': ['Caffeine',
   'Liquorice Extract',
   'Vitamin A',
   'Green Tea',
   'Almond Oil',
   'Wheat Germ Oil',
   'Chamomile Extract',
   'Allantoin',
   'Royal Jelly',
   'Panthenol',
   'Collagen'],
  'concerns': [['Hyperpigmentation& dark spots',
    'Dark circles “blue- brown- black” & puffiness']],
  'category': ['Skin Care', 'Eye cream'],
  'price': '225.00',
  'product_file': None,
  'best_seller': True,
  'new_arrived': False},
 {'product_id': 7,
  'name': 'Spleet Facial wash',
  'description': 'Spleet face wash with an unique the Canadian balanced formula that keeps skin pH balanced to be safe and  suitable for all skin types that work with 5 power to give marvels 5  effects and effectiveness to show the beauty of the skin naturally and safely, as it helps to clean the skin for getting rid  of accumulated makeup and debris to gives it a sense of freshness with an effect in lightening and enlightening the skin significantly, also helps it get rid of acne, pimples and reduce the appearance of enlarged pores and give  a tightening of the skin because it is rich in collagen stimuli plus natural collagen with important vitamins those rejuvenate and tighten the skin to help it fight the appearance of early wrinkles leaving the skin deeply moisturized along the day.\r\nComposition: \r\n•\tAloe Vera Extract.\r\n•\tJojoba Oil.\r\n•\tTocopherol.\r\n•\tCollagen.\r\n•\tCamellia Sinensis Extract.\r\n•\tGlycyrrhiza Glabra Leaf Extract.\r\n•\tSalicylic Acid.\r\n•\tGlycolic Acid.\r\n•\tGlycerin.\r\n•\tGlycine.\r\n\r\nIndicated for:\r\n\r\n• It cleans the skin effectively and safely.\r\n• Lighten skin color.\r\n• Moisturizing the skin deeply.\r\n• Treating Acne and pimples.\r\n• Rejuvenation and tightening of the skin.\r\n•\tReduce the appearance of enlarged pores\r\n• Suitable for daily use.\r\n• A very small amount is sufficient.\r\n• Easy to rinse off.\r\n• Reduces fatty secretions.\r\n• Light and distinct scent.\r\n• Free of soap and does not cause clogged pores.\r\n\r\nApplication: \r\nApply a small amount on the face with a little of water, gently massage and then rinse, twice daily.\r\n\r\nPackage:\r\n200 ml.',
  'ingredients': ['Aloe Vera Extract',
   'Jojoba Oil',
   'Tocopherol',
   'Collagen',
   'Camellia Sinensis Extract',
   'Glycyrrhiza Glabra Leaf Extract',
   'Salicylic Acid',
   'Glycolic Acid',
   'Glycerin',
   'Glycine'],
  'concerns': [['Acne& acne spots',
    'Hyperpigmentation& dark spots',
    'Dull& pale skin',
    'Eczema & Dry skin']],
  'category': ['Skin Care', 'Cleansers'],
  'price': '220.00',
  'product_file': None,
  'best_seller': True,
  'new_arrived': False},
 {'product_id': 12,
  'name': 'Aceto-V Feminine Intimate wash',
  'description': 'Acet-V is a feminine Intimate wash with unique combination of real treatment for vaginal infection either bacterial or fungal plus moisturizers, tightening agents to enjoy daily activities& sexual intercourse. \r\nComposition:- \r\n*Chlorhexidine gluconate.\r\n *Cetrimide. \r\n*Aloe Vera.\r\n*Chamomile.\r\n*Glycerin.\r\n\r\nIndicated for:\r\n•\tBacterial vaginosis. \r\n•\tVaginal candidiasis.\r\n•\tAtrophic Vaginitis.\r\n•\tVaginal irritation& itching. \r\n•\tPersonal hygiene during menstrual cycle.\r\n•\tPersonal hygiene after sexual intercourse.\r\n•\tPersonal hygiene after Labor.\r\n•\tTighten the vagina.\r\nApplication:-\r\nApplied directly without dilution, once per day for external use only.\r\n\r\nPackage:\r\n250ml.',
  'ingredients': ['Chlorhexidine gluconate',
   'Cetrimide',
   'Aloe Vera',
   'Chamomile',
   'Glycerin'],
  'concerns': [['Sensitive areas& Bikini area brightening']],
  'category': ['Personal Care', 'Cleansers'],
  'price': '90.00',
  'product_file': None,
  'best_seller': False,
  'new_arrived': False}]

In [6]:
df = pd.DataFrame(response['data']['products'])

In [7]:
df

,product_id,name,description,ingredients,concerns,category,price,product_file,best_seller,new_arrived
0,1,Herforte Lotion Spray (to fill in gaps and tre...,Hair forte is a mixture of natural extracts an...,"[Jojoba Oil Extract, Garlic Oil Extract, Nigel...",[[Hair loss]],"[Hair Care, Hair spray& lotion]",200.00,None,True,False
1,2,Hairforte Shampoo (for treating hair loss and ...,Hair Forte shampoo is an effective combination...,"[Caffeine, Jojoba Oil, Lavender Oil, Coconut O...",[[Dandruff]],"[Hair Care, Shampoos]",150.00,None,True,False
2,3,Valdo moisturizing cream,Valdo Moisturizing Cream\r\n-The best moisturi...,"[Panthenol (Vitamin B5), Aloe Vera, Calendula,...",[[Eczema & Dry skin]],"[Skin Care, Moisturizer]",80.00,None,True,False
3,4,Spleet Cream Scrub (Steam Alternative + Acne T...,Spleet is a gentle exfoliating cream with a un...,"[Urea, Salicylic Acid, Lactic Acid, Tea Tree O...","[[Strawberry skin treatment, Acne& acne spots,...","[Personal Care, Soft peel and Exfoliant]",100.00,None,True,False
4,5,Spleet Lightening Cream (for treating pigmenta...,Spleet whitening cream offers the strongest un...,"[Alpha-Arbutin, Kojic Acid, Niacinamide, Licor...","[[Hyperpigmentation& dark spots, Sensitive are...","[Skin Care, Whitening cream]",100.00,None,True,False
5,6,Spleet Eye Contour Cream (for treating dark ci...,An unique potent mix of natural ingredients...,"[Caffeine, Liquorice Extract, Vitamin A, Green...","[[Hyperpigmentation& dark spots, Dark circles ...","[Skin Care, Eye cream]",225.00,None,True,False
6,7,Spleet Facial wash,Spleet face wash with an unique the Canadian b...,"[Aloe Vera Extract, Jojoba Oil, Tocopherol, Co...","[[Acne& acne spots, Hyperpigmentation& dark sp...","[Skin Care, Cleansers]",220.00,None,True,False
7,12,Aceto-V Feminine Intimate wash,Acet-V is a feminine Intimate wash with unique...,"[Chlorhexidine gluconate, Cetrimide, Aloe Vera...",[[Sensitive areas& Bikini area brightening]],"[Personal Care, Cleansers]",90.00,None,False,False

In [8]:
import pandas as pd



# Function to flatten nested lists (like 'concerns')
def flatten_list(nested_list):
    if isinstance(nested_list, list):
        if not nested_list:
            return []
        elif all(isinstance(item, str) for item in nested_list):
            return nested_list
        else:
            return [item for sublist in nested_list for item in (sublist if isinstance(sublist, list) else [sublist])]
    return nested_list

# Preprocess the DataFrame
def preprocess_dataframe(df):
    # Create a copy to avoid modifying the original
    processed_df = df.copy()
    
    # Handle nested lists
    if 'concerns' in processed_df.columns:
        processed_df['concerns'] = processed_df['concerns'].apply(flatten_list)
        processed_df['concerns'] = processed_df['concerns'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)
    
    if 'ingredients' in processed_df.columns:
        processed_df['ingredients'] = processed_df['ingredients'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)
        
    if 'category' in processed_df.columns:
        processed_df['category'] = processed_df['category'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)
    
    # Clean text fields - remove excessive whitespace and special characters
    text_columns = ['name', 'description']
    for col in text_columns:
        if col in processed_df.columns:
            # Replace multiple whitespaces with a single space
            processed_df[col] = processed_df[col].str.replace(r'\s+', ' ', regex=True)
            # Replace \r\n with space
            processed_df[col] = processed_df[col].str.replace(r'\r\n', ' ', regex=True)
            # Trim whitespace
            processed_df[col] = processed_df[col].str.strip()
    
    # Extract short description (first 100 characters)
    if 'description' in processed_df.columns:
        processed_df['short_description'] = processed_df['description'].apply(
            lambda x: x[:100] + '...' if isinstance(x, str) and len(x) > 100 else x
        )
    
    # Convert price to numeric
    if 'price' in processed_df.columns:
        processed_df['price'] = pd.to_numeric(processed_df['price'], errors='coerce')
    
    # Handle None values
    processed_df = processed_df.fillna(value={
        'product_file': 'No file',
        'ingredients': 'Not specified',
        'concerns': 'Not specified'
    })
    
    # Extract parentheses content from name as a feature
    if 'name' in processed_df.columns:
        processed_df['name_attributes'] = processed_df['name'].str.extract(r'\((.*?)\)', expand=False)
        # Clean up the main name by removing parentheses content
        processed_df['clean_name'] = processed_df['name'].str.replace(r'\s*\(.*?\)\s*', ' ', regex=True).str.strip()
    
    return processed_df

# Apply preprocessing
processed_df = preprocess_dataframe(df)

# Display the preprocessed DataFrame
print("Original DataFrame:")
df.head()

Original DataFrame:

,product_id,name,description,ingredients,concerns,category,price,product_file,best_seller,new_arrived
0,1,Herforte Lotion Spray (to fill in gaps and tre...,Hair forte is a mixture of natural extracts an...,"[Jojoba Oil Extract, Garlic Oil Extract, Nigel...",[[Hair loss]],"[Hair Care, Hair spray& lotion]",200.00,None,True,False
1,2,Hairforte Shampoo (for treating hair loss and ...,Hair Forte shampoo is an effective combination...,"[Caffeine, Jojoba Oil, Lavender Oil, Coconut O...",[[Dandruff]],"[Hair Care, Shampoos]",150.00,None,True,False
2,3,Valdo moisturizing cream,Valdo Moisturizing Cream\r\n-The best moisturi...,"[Panthenol (Vitamin B5), Aloe Vera, Calendula,...",[[Eczema & Dry skin]],"[Skin Care, Moisturizer]",80.00,None,True,False
3,4,Spleet Cream Scrub (Steam Alternative + Acne T...,Spleet is a gentle exfoliating cream with a un...,"[Urea, Salicylic Acid, Lactic Acid, Tea Tree O...","[[Strawberry skin treatment, Acne& acne spots,...","[Personal Care, Soft peel and Exfoliant]",100.00,None,True,False
4,5,Spleet Lightening Cream (for treating pigmenta...,Spleet whitening cream offers the strongest un...,"[Alpha-Arbutin, Kojic Acid, Niacinamide, Licor...","[[Hyperpigmentation& dark spots, Sensitive are...","[Skin Care, Whitening cream]",100.00,None,True,False

In [9]:
print("\nPreprocessed DataFrame:")
processed_df.head()

Preprocessed DataFrame:

,product_id,name,description,ingredients,concerns,category,price,product_file,best_seller,new_arrived,short_description,name_attributes,clean_name
0,1,Herforte Lotion Spray (to fill in gaps and tre...,Hair forte is a mixture of natural extracts an...,"Jojoba Oil Extract, Garlic Oil Extract, Nigell...",Hair loss,"Hair Care, Hair spray& lotion",200.0,No file,True,False,Hair forte is a mixture of natural extracts an...,to fill in gaps and treat alopecia,Herforte Lotion Spray
1,2,Hairforte Shampoo (for treating hair loss and ...,Hair Forte shampoo is an effective combination...,"Caffeine, Jojoba Oil, Lavender Oil, Coconut Oi...",Dandruff,"Hair Care, Shampoos",150.0,No file,True,False,Hair Forte shampoo is an effective combination...,for treating hair loss and dandruff + deep moi...,Hairforte Shampoo
2,3,Valdo moisturizing cream,Valdo Moisturizing Cream -The best moisturizin...,"Panthenol (Vitamin B5), Aloe Vera, Calendula, ...",Eczema & Dry skin,"Skin Care, Moisturizer",80.0,No file,True,False,Valdo Moisturizing Cream -The best moisturizin...,NaN,Valdo moisturizing cream
3,4,Spleet Cream Scrub (Steam Alternative + Acne T...,Spleet is a gentle exfoliating cream with a un...,"Urea, Salicylic Acid, Lactic Acid, Tea Tree Oi...","Strawberry skin treatment, Acne& acne spots, H...","Personal Care, Soft peel and Exfoliant",100.0,No file,True,False,Spleet is a gentle exfoliating cream with a un...,Steam Alternative + Acne Treatment,Spleet Cream Scrub
4,5,Spleet Lightening Cream (for treating pigmenta...,Spleet whitening cream offers the strongest un...,"Alpha-Arbutin, Kojic Acid, Niacinamide, Licori...","Hyperpigmentation& dark spots, Sensitive areas...","Skin Care, Whitening cream",100.0,No file,True,False,Spleet whitening cream offers the strongest un...,for treating pigmentation and acne scars,Spleet Lightening Cream

In [23]:


# Create keyword columns for easier searching
def create_keyword_columns(df):
    # Create a column that combines all searchable text
    df['search_text'] = (
        df['clean_name'].fillna('') + ' ' + 
        df['description'].fillna('') + ' ' + 
        df['ingredients'].fillna('') + ' ' + 
        df['concerns'].fillna('') + ' ' + 
        df['category'].fillna('')
    )
    
    # Convert search text to lowercase for case-insensitive search
    df['search_text'] = df['search_text'].str.lower()
    
    # Create price range categories
    if 'price' in df.columns:
        bins = [0, 50, 100, 200, 500, float('inf')]
        labels = ['0-50', '51-100', '101-200', '201-500', '500+']
        df['price_range'] = pd.cut(df['price'], bins=bins, labels=labels, right=False)
    
    return df

# Apply keyword enhancements
enhanced_df = create_keyword_columns(processed_df)

# Sample queries to demonstrate the functionality
def query_products(df, search_term=None, category=None, concerns=None, price_min=None, price_max=None, has_ingredient=None , best_seller=None , new_arrived=None):
    result = df.copy()
    
    if search_term:
        search_term = search_term.lower()
        result = result[result['search_text'].str.contains(search_term, na=False)]
    
    if category:
        result = result[result['category'].str.contains(category, case=False, na=False)]
        
    if concerns:
        result = result[result['concerns'].str.contains(concerns, case=False, na=False)]
    
    if price_min is not None:
        result = result[result['price'] >= price_min]
        
    if price_max is not None:
        result = result[result['price'] <= price_max]
    
    if has_ingredient:
        result = result[result['ingredients'].str.contains(has_ingredient, case=False, na=False)]
        
    if best_seller:
        result = result[result['best_seller'] == best_seller]
        
    if new_arrived:
        result = result[result['new_arrived'] == new_arrived]
    

    return result[['product_id', 'name', 'description', 'ingredients', 'concerns', 'category' , "price" , "best_seller" , "new_arrived"]]

# Examples of using the query function
print("\nExample Query - Search for 'hair loss':")
result1 = query_products(enhanced_df, search_term='hair Dandruff')
result1

Example Query - Search for 'hair loss':

Empty DataFrame
Columns: [product_id, name, description, ingredients, concerns, category, price, best_seller, new_arrived]
Index: []

In [15]:
enhanced_df.iloc[0][-2]

C:\Users\DELL\AppData\Local\Temp\ipykernel_17936\3106559214.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  enhanced_df.iloc[0][-2]

'herforte lotion spray hair forte is a mixture of natural extracts and extracts of the most important hair oils with anti-dandruff agent, to be a quick treatment for hair loss, guaranteed and tested by dermatologists for fortifying hair & increase hair shaft strength to prevent hair loss. also, hair forte spray stimulates hair germination to be an effective solution to fill the frontal spaces in women and men, in addition to treating dandruff & itching associated with dryness and inflammation of the scalp, hair forte spray is suitable for all hair types even oily & dry scalp. composition:- hair forte spray with its unique formula to be effective in stimulating the blood circulation of the scalp and hair follicles to strengthen and nourish them to prevent hair loss and also to stimulate root germination for the growth of healthy, thick, long and strong hair without dandruff. • jojoba oil extract. • garlic oil extract. • nigella. • rosemary. • caffeine. • thyme oil. • salicylic acid. • panthenol. • aloe vera. • vitamin e. indicated for: *diffuse hair fall. *adjuvant therapy for alopecia areata. *controls split ends, roughness, dryness& brittleness of hair. *controls dandruff. application: spray onto wet or dry hair& scalp “6 pump” suitable amount then massage& style as usual, once or twice daily preferably start from the forehead to back of the head in a circular movement or as directed by physician. package: 120 ml. jojoba oil extract, garlic oil extract, nigella, rosemary, caffeine, thyme oil, salicylic acid, panthenol, aloe vera, vitamin e hair loss hair care, hair spray& lotion'

In [19]:
# Examples of using the query function
result1 = query_products(enhanced_df, search_term=' Care')
result1

,product_id,name,description,ingredients,concerns,category,price,best_seller,new_arrived
0,1,Herforte Lotion Spray (to fill in gaps and tre...,Hair forte is a mixture of natural extracts an...,"Jojoba Oil Extract, Garlic Oil Extract, Nigell...",Hair loss,"Hair Care, Hair spray& lotion",200.0,True,False
1,2,Hairforte Shampoo (for treating hair loss and ...,Hair Forte shampoo is an effective combination...,"Caffeine, Jojoba Oil, Lavender Oil, Coconut Oi...",Dandruff,"Hair Care, Shampoos",150.0,True,False
2,3,Valdo moisturizing cream,Valdo Moisturizing Cream -The best moisturizin...,"Panthenol (Vitamin B5), Aloe Vera, Calendula, ...",Eczema & Dry skin,"Skin Care, Moisturizer",80.0,True,False
3,4,Spleet Cream Scrub (Steam Alternative + Acne T...,Spleet is a gentle exfoliating cream with a un...,"Urea, Salicylic Acid, Lactic Acid, Tea Tree Oi...","Strawberry skin treatment, Acne& acne spots, H...","Personal Care, Soft peel and Exfoliant",100.0,True,False
4,5,Spleet Lightening Cream (for treating pigmenta...,Spleet whitening cream offers the strongest un...,"Alpha-Arbutin, Kojic Acid, Niacinamide, Licori...","Hyperpigmentation& dark spots, Sensitive areas...","Skin Care, Whitening cream",100.0,True,False
5,6,Spleet Eye Contour Cream (for treating dark ci...,An unique potent mix of natural ingredients th...,"Caffeine, Liquorice Extract, Vitamin A, Green ...","Hyperpigmentation& dark spots, Dark circles “b...","Skin Care, Eye cream",225.0,True,False
6,7,Spleet Facial wash,Spleet face wash with an unique the Canadian b...,"Aloe Vera Extract, Jojoba Oil, Tocopherol, Col...","Acne& acne spots, Hyperpigmentation& dark spot...","Skin Care, Cleansers",220.0,True,False
7,12,Aceto-V Feminine Intimate wash,Acet-V is a feminine Intimate wash with unique...,"Chlorhexidine gluconate, Cetrimide, Aloe Vera,...",Sensitive areas& Bikini area brightening,"Personal Care, Cleansers",90.0,False,False

In [69]:
ingredients_set = set()
for ingredients in df['ingredients'].to_list():
    if isinstance(ingredients, list):
        for ingredient in ingredients:
            if isinstance(ingredient, (list, tuple)) and ingredient:
                ingredients_set.add(ingredient[0])  # Add first element if it's a tuple/list
            elif ingredient:  # Add the ingredient if it's a non-empty string
                ingredients_set.add(ingredient)
print(ingredients_set)

{'Vitamin C', 'Tocopherol', 'Chamomile Extract', 'Panthenol', 'Zinc Pyrithione', 'Dimethicone', 'Vitamin E', 'Aloe Vera Extract', 'Salicylic acid', 'Jojoba Oil Extract', 'Glycolic Acid', 'Glycine', 'Jojoba Oil', 'Royal Jelly', 'Chlorhexidine gluconate', 'Chamomile', 'Zinc Oxide', 'Olive Oil', 'Licorice', 'Green Tea', 'Triclosan', 'Panthenol (Vitamin B5)', 'Urea', 'Vitamin A', 'Wheat Germ Oil', 'Cetrimide', 'Calendula', 'Nigella', 'Rosemary Oil', 'Salicylic Acid', 'Glycerin', 'Collagen', 'Lavender Oil', 'Coconut Oil', 'Garlic Oil Extract', 'Rosemary', 'Kojic Acid', 'Glycyrrhiza Glabra Leaf Extract', 'Garlic Extract', 'Aloe Vera', 'Allantoin', 'Niacinamide', 'Caffeine', 'Almond Oil', 'Alpha-Arbutin', 'Camellia Sinensis Extract', 'Lactic Acid', 'Thyme Oil', 'Tea Tree Oil', 'Liquorice Extract'}

In [67]:
query_products(enhanced_df, best_seller = True , category='Hair ')

,product_id,name,description,ingredients,concerns,category,price,best_seller,new_arrived
0,1,Herforte Lotion Spray (to fill in gaps and tre...,Hair forte is a mixture of natural extracts an...,"Jojoba Oil Extract, Garlic Oil Extract, Nigell...",Hair loss,"Hair Care, Hair spray& lotion",200.0,True,False
1,2,Hairforte Shampoo (for treating hair loss and ...,Hair Forte shampoo is an effective combination...,"Caffeine, Jojoba Oil, Lavender Oil, Coconut Oi...",Dandruff,"Hair Care, Shampoos",150.0,True,False

In [49]:
print("\nExample Query - Products with price less than 250:")
result2 = query_products(enhanced_df, price_max=250)
result2

Example Query - Products with price less than 250:

,product_id,clean_name,short_description,price,category,ingredients
0,1,Herforte Lotion Spray,Hair forte is a mixture of natural extracts an...,200.0,"Hair Care, Hair spray& lotion","Jojoba Oil Extract, Garlic Oil Extract, Nigell..."
1,2,Hairforte Shampoo,Hair Forte shampoo is an effective combination...,150.0,"Hair Care, Shampoos","Caffeine, Jojoba Oil, Lavender Oil, Coconut Oi..."
2,3,Valdo moisturizing cream,Valdo Moisturizing Cream -The best moisturizin...,80.0,"Skin Care, Moisturizer","Panthenol (Vitamin B5), Aloe Vera, Calendula, ..."
3,4,Spleet Cream Scrub,Spleet is a gentle exfoliating cream with a un...,100.0,"Personal Care, Soft peel and Exfoliant","Urea, Salicylic Acid, Lactic Acid, Tea Tree Oi..."
4,5,Spleet Lightening Cream,Spleet whitening cream offers the strongest un...,100.0,"Skin Care, Whitening cream","Alpha-Arbutin, Kojic Acid, Niacinamide, Licori..."
5,6,Spleet Eye Contour Cream,An unique potent mix of natural ingredients th...,225.0,"Skin Care, Eye cream","Caffeine, Liquorice Extract, Vitamin A, Green ..."
6,7,Spleet Facial wash,Spleet face wash with an unique the Canadian b...,220.0,"Skin Care, Cleansers","Aloe Vera Extract, Jojoba Oil, Tocopherol, Col..."
7,12,Aceto-V Feminine Intimate wash,Acet-V is a feminine Intimate wash with unique...,90.0,"Personal Care, Cleansers","Chlorhexidine gluconate, Cetrimide, Aloe Vera,..."

In [53]:


print("\nExample Query - Products with Aloe Vera:")
result3 = query_products(enhanced_df, has_ingredient='Jojoba')
result3

Example Query - Products with Aloe Vera:

,product_id,clean_name,short_description,price,category,ingredients
0,1,Herforte Lotion Spray,Hair forte is a mixture of natural extracts an...,200.0,"Hair Care, Hair spray& lotion","Jojoba Oil Extract, Garlic Oil Extract, Nigell..."
1,2,Hairforte Shampoo,Hair Forte shampoo is an effective combination...,150.0,"Hair Care, Shampoos","Caffeine, Jojoba Oil, Lavender Oil, Coconut Oi..."
6,7,Spleet Facial wash,Spleet face wash with an unique the Canadian b...,220.0,"Skin Care, Cleansers","Aloe Vera Extract, Jojoba Oil, Tocopherol, Col..."

In [48]:
enhanced_df

,product_id,name,description,ingredients,concerns,category,price,product_file,best_seller,new_arrived,short_description,name_attributes,clean_name,search_text,price_range
0,1,Herforte Lotion Spray (to fill in gaps and tre...,Hair forte is a mixture of natural extracts an...,"Jojoba Oil Extract, Garlic Oil Extract, Nigell...",Hair loss,"Hair Care, Hair spray& lotion",200.0,No file,True,False,Hair forte is a mixture of natural extracts an...,to fill in gaps and treat alopecia,Herforte Lotion Spray,herforte lotion spray hair forte is a mixture ...,201-500
1,2,Hairforte Shampoo (for treating hair loss and ...,Hair Forte shampoo is an effective combination...,"Caffeine, Jojoba Oil, Lavender Oil, Coconut Oi...",Dandruff,"Hair Care, Shampoos",150.0,No file,True,False,Hair Forte shampoo is an effective combination...,for treating hair loss and dandruff + deep moi...,Hairforte Shampoo,hairforte shampoo hair forte shampoo is an eff...,101-200
2,3,Valdo moisturizing cream,Valdo Moisturizing Cream -The best moisturizin...,"Panthenol (Vitamin B5), Aloe Vera, Calendula, ...",Eczema & Dry skin,"Skin Care, Moisturizer",80.0,No file,True,False,Valdo Moisturizing Cream -The best moisturizin...,NaN,Valdo moisturizing cream,valdo moisturizing cream valdo moisturizing cr...,51-100
3,4,Spleet Cream Scrub (Steam Alternative + Acne T...,Spleet is a gentle exfoliating cream with a un...,"Urea, Salicylic Acid, Lactic Acid, Tea Tree Oi...","Strawberry skin treatment, Acne& acne spots, H...","Personal Care, Soft peel and Exfoliant",100.0,No file,True,False,Spleet is a gentle exfoliating cream with a un...,Steam Alternative + Acne Treatment,Spleet Cream Scrub,spleet cream scrub spleet is a gentle exfoliat...,101-200
4,5,Spleet Lightening Cream (for treating pigmenta...,Spleet whitening cream offers the strongest un...,"Alpha-Arbutin, Kojic Acid, Niacinamide, Licori...","Hyperpigmentation& dark spots, Sensitive areas...","Skin Care, Whitening cream",100.0,No file,True,False,Spleet whitening cream offers the strongest un...,for treating pigmentation and acne scars,Spleet Lightening Cream,spleet lightening cream spleet whitening cream...,101-200
5,6,Spleet Eye Contour Cream (for treating dark ci...,An unique potent mix of natural ingredients th...,"Caffeine, Liquorice Extract, Vitamin A, Green ...","Hyperpigmentation& dark spots, Dark circles “b...","Skin Care, Eye cream",225.0,No file,True,False,An unique potent mix of natural ingredients th...,for treating dark circles + expression lines +...,Spleet Eye Contour Cream,spleet eye contour cream an unique potent mix ...,201-500
6,7,Spleet Facial wash,Spleet face wash with an unique the Canadian b...,"Aloe Vera Extract, Jojoba Oil, Tocopherol, Col...","Acne& acne spots, Hyperpigmentation& dark spot...","Skin Care, Cleansers",220.0,No file,True,False,Spleet face wash with an unique the Canadian b...,NaN,Spleet Facial wash,spleet facial wash spleet face wash with an un...,201-500
7,12,Aceto-V Feminine Intimate wash,Acet-V is a feminine Intimate wash with unique...,"Chlorhexidine gluconate, Cetrimide, Aloe Vera,...",Sensitive areas& Bikini area brightening,"Personal Care, Cleansers",90.0,No file,False,False,Acet-V is a feminine Intimate wash with unique...,NaN,Aceto-V Feminine Intimate wash,aceto-v feminine intimate wash acet-v is a fem...,51-100

In [18]:
class DfManager():
    
    def __init__(self, df):
        self.df = df
        self.__clean_df()
        
    def __clean_df(self):
        self.df['price'] = self.df['price'].astype(float)
        return self.df
        
    def get_df(self):
        return self.df

    def get_category_set(self):
        category_set = set()
        for category in self.df['category'].to_list():  
            for c in category:
                category_set.add(c)
        return category_set

    def get_concerns_set(self):
        concerns_set = set()
        for concerns in self.df['concerns'].to_list():
            for concern in concerns:
                for c in concern:
                    concerns_set.add(c)
        return concerns_set

In [19]:
df_manager = DfManager(df)

In [24]:
df_manager.get_df()

,product_id,name,description,ingredients,concerns,category,price,product_file
0,1,Herforte Lotion Spray (to fill in gaps and tre...,Hair forte is a mixture of natural extracts an...,[],[[Hair loss]],"[Hair Care, Hair spray& lotion]",200.0,None
1,2,Hairforte Shampoo (for treating hair loss and ...,Hair Forte shampoo is an effective combination...,[],[[Dandruff]],"[Hair Care, Shampoos]",150.0,None
2,3,Valdo moisturizing cream,Valdo Moisturizing Cream\r\n-The best moisturi...,[],[[Eczema & Dry skin]],"[Skin Care, Moisturizer]",80.0,None
3,4,Spleet Cream Scrub (Steam Alternative + Acne T...,Spleet is a gentle exfoliating cream with a un...,[],"[[Strawberry skin treatment, Acne& acne spots,...","[Personal Care, Soft peel and Exfoliant]",100.0,None
4,5,Spleet Lightening Cream (for treating pigmenta...,Spleet whitening cream offers the strongest un...,[],"[[Hyperpigmentation& dark spots, Sensitive are...","[Skin Care, Whitening cream]",100.0,None
5,6,Spleet Eye Contour Cream (for treating dark ci...,An unique potent mix of natural ingredients...,[],"[[Hyperpigmentation& dark spots, Dark circles ...","[Skin Care, Eye cream]",225.0,None
6,7,Spleet Facial wash,Spleet face wash with an unique the Canadian b...,[],"[[Acne& acne spots, Hyperpigmentation& dark sp...","[Skin Care, Cleansers]",220.0,None
7,12,Aceto-V Feminine Intimate wash,Acet-V is a feminine Intimate wash with unique...,[],[[Sensitive areas& Bikini area brightening]],"[Personal Care, Cleansers]",90.0,None
8,14,"Valdo Sunscreen Lotion (No Oxidation, No Sweat...",الحمايةمن االلتهاباتوجفاف البشرة.\r\nيحمي من...,[],[[Eczema & Dry skin]],"[Skin Care, Sun screen]",350.0,None
9,15,Hairforte Oil Replacement Cream (for treating ...,Hairfort cream is a special formula composed...,[],[[Dandruff]],"[Hair Care, Oil replacement]",180.0,None
10,19,"Get ready for Eid with a box of lightening, en...",Interpharma made a package to lighten and enli...,[],[[Dull& pale skin]],"[Skin Care, Moisturizer]",370.0,None
11,23,Package to lighten bikini and sensitive areas,Bikini Lightening & Sensitive Areas Package (4...,[],[[Sensitive areas& Bikini area brightening]],"[Personal Care, Cleansers]",310.0,None
12,24,Deep Moisturizing Hair Package (3pcs),Deep Moisturizing Hair Package (3pcs) \r\n And...,[],[[Dandruff]],"[Hair Care, Repairing & hair moisturizing]",470.0,None
13,25,"Package treatment of dandruff, voids and falli...","Package treatment of dandruff, voids and falli...",[],[[Hair loss]],"[Hair Care, Repairing & hair moisturizing]",299.0,None
14,26,Post-peeling skincare package (5pcs),Post-peeling skincare package (5pcs)\r\nTo mai...,[],[[Acne& acne spots]],"[Skin Care, Cleansers]",775.0,None
15,27,Winter Skin Care Package With Complete Care (6...,Winter Skin Care Package With Complete Care (6...,[],[[Dull& pale skin]],"[Skin Care, Soft peel and Exfoliant]",950.0,None
16,28,Skin & Eye Contour Enlightenment Package (4pcs),Skin & Eye Contour Enlightenment Package (4pcs...,[],[[Dark circles “blue- brown- black” & puffiness]],"[Skin Care, Whitening cream]",520.0,None
17,29,Lightening and freshness routine with Rana Reda,Daily freshness package\r\nStop for a minute a...,[],[[Dull& pale skin]],"[Skin Care, Cleansers]",570.0,None
18,31,Valdo Anti _aging Serum,"Discover the secret to youthful, radiant skin ...",[],[[Dull& pale skin]],"[Skin Care, Toner “coming soon”]",375.0,None
19,32,Three steps and lighten up to 3 shades,How can you make Ramadan an opportunity for cl...,[],[[Acne& acne spots]],"[Skin Care, Cleansers]",365.0,None
20,33,Lasting softness and hydration,Why is moisturizing your skin during Ramadan d...,[],[[Eczema & Dry skin]],"[Skin Care, Moisturizer]",260.0,None
21,34,Skin that speaks freshness,How can you ensure dry skin during fasting?\r\...,[],[[Dull& pale skin]],"[Skin Care, Cleansers]",255.0,None
22,35,"Eyes without wrinkles, skin without pigmentation","With minimal effort and faster results, you'll...",[],[[Hyperpigmentation& dark spots]],"[Skin Care, Eye cream]",285.0,None
23,36,Valdo Milk Body Lotion,"Experience smooth, hydrated, and radiant skin ...",[],[[Strawberry skin treatment]],"[Skin Care, Moisturizer]",275.0,None

In [7]:
category_set = set()

for category in df['category'].to_list():
  for c in category:
    category_set.add(c)

category_set

{'Cleansers',
 'Eye cream',
 'Hair Care',
 'Hair spray& lotion',
 'Moisturizer',
 'Oil replacement',
 'Personal Care',
 'Repairing & hair moisturizing',
 'Shampoos',
 'Skin Care',
 'Soft peel and Exfoliant',
 'Sun screen',
 'Toner “coming soon”',
 'Whitening cream'}

In [8]:
concerns_set = set()

for concerns in df['concerns'].to_list():
    for concern in concerns:
        for c in concern:
            concerns_set.add(c)

concerns_set

{'Acne& acne spots',
 'Dandruff',
 'Dark circles “blue- brown- black” & puffiness',
 'Dull& pale skin',
 'Eczema & Dry skin',
 'Hair loss',
 'Hyperpigmentation& dark spots',
 'Sensitive areas& Bikini area brightening',
 'Strawberry skin treatment'}

In [10]:


# Filter by categories
categories = ['Hair Care', 'Shampoos']
concerns = ['Hair loss', 'Dandruff']

category_matches = df[df['category'].apply(
        lambda x: any(cat.lower() in c.lower() for cat in categories for c in x)
    )]
    
# Further filter by concerns
matches = category_matches[category_matches['concerns'].apply(
        lambda x: any(con.lower() in c[0].lower() for con in concerns for c in x if c)
    )]

In [12]:
matches.to_dict('records')

[{'product_id': 1,
  'name': 'Herforte Lotion Spray (to fill in gaps and treat alopecia)',
  'description': 'Hair forte is a mixture of natural extracts and extracts of the most important hair oils with anti-dandruff agent, to be a quick treatment for hair loss, guaranteed and tested by dermatologists for fortifying hair & increase hair shaft strength to prevent hair loss. Also, Hair forte spray stimulates hair germination to be an effective solution to fill the frontal spaces in women and men, in addition to treating dandruff & itching associated with dryness and inflammation of the scalp, Hair forte spray is suitable for all hair types even oily & dry scalp.\r\n\r\nComposition:-\r\nHair forte spray with its unique formula to be effective in stimulating the blood circulation of the scalp and hair follicles to strengthen and nourish them to prevent hair loss and also to stimulate root germination for the growth of healthy, thick, long and strong hair without dandruff.\r\n\r\n•\tJojoba Oil Extract.\r\n•\tGarlic Oil Extract.\r\n•\tNigella.\r\n•\tRosemary.\r\n•\tCaffeine.\r\n•\tThyme Oil.\r\n•\tSalicylic acid.\r\n•\tPanthenol.\r\n•\tAloe Vera.\r\n•\tVitamin E.\r\nIndicated for:\r\n*Diffuse hair fall.\r\n*Adjuvant therapy for alopecia areata. \r\n*Controls split ends, roughness, dryness& brittleness of hair. \r\n*Controls dandruff.\r\n\r\nApplication:\r\nSpray onto wet or dry hair& scalp “6 pump” suitable amount then massage& style as usual, once or twice daily preferably start from the forehead to back of the head in a circular movement or as directed by physician.\r\n\r\nPackage:\r\n 120 ml.',
  'ingredients': [],
  'concerns': [['Hair loss']],
  'category': ['Hair Care', 'Hair spray& lotion'],
  'price': '200.00',
  'product_file': None},
 {'product_id': 2,
  'name': 'Hairforte Shampoo (for treating hair loss and dandruff + deep moisturizing)',
  'description': 'Hair Forte shampoo is an effective combination of anti-dandruff with natural extracts& important oils for hair to get rid of dandruff while nourishing &moisturizing hair to reduce hair falling also it helps in stimulating hair growth, Hair forte shampoo For Both Treated hair and Normal one.\r\n\r\nComposition:\r\n\r\n•\tCaffeine.\r\n•\tJojoba Oil.\r\n•\tLavender Oil.\r\n•\tCoconut Oil.\r\n•\tOlive Oil.\r\n•\tRosemary Oil.\r\n•\tVitamin E.\r\n•\tPanthenol.\r\n•\tAloe Vera.\r\n•\tZinc Pyrithione.\r\n•\tGarlic Extract.\r\n•\tTriclosan.\r\nIndicated for:\r\n\r\n*Treatment of dandruff.\r\n*Diffuse hair fall.\r\n*Adjuvant therapy for alopecia areata. \r\n*Controls split ends, roughness, dryness& brittleness of hair.\r\n\r\n\r\nApplication:\r\nApply a sufficient amount on wet hair and scalp, with gentle massage then rinse well with water from 1: 2 times weekly.\r\nPackage:\r\n 120 ml.',
  'ingredients': [],
  'concerns': [['Dandruff']],
  'category': ['Hair Care', 'Shampoos'],
  'price': '150.00',
  'product_file': None},
 {'product_id': 15,
  'name': 'Hairforte Oil Replacement Cream (for treating frizz, split ends and tangles)',
  'description': 'Hairfort  cream  is a special formula composed of the most important hair oils, natural extracts and vitamins to moisturize, condition and deeply nourishes hair from inside with its creamy texture to get rid of  tangling and hair frizz  leaving that healthy, smooth and shiny plus restoring the hair bonds to repair the hair shaft and reducing of hair split ends.  \r\n•\tAlso, Hair forte cream protects hair from damage by external factors as ultraviolet rays & hairdressers and works as a protective layer for hair strands to reduce damage to reduce hair loss.\r\n\r\n•\tHair forte cream is suitable for all types of hair either oily hair and or normal hair.',
  'ingredients': [],
  'concerns': [['Dandruff']],
  'category': ['Hair Care', 'Oil replacement'],
  'price': '180.00',
  'product_file': None},
 {'product_id': 24,
  'name': 'Deep Moisturizing Hair Package (3pcs)',
  'description': 'Deep Moisturizing Hair Package (3pcs) \r\n And stop the falling, the frizzy bombardments \r\nFrom the Hair Fort collection in 3 steps: \r\n\r\nHair Forte Shampoo to moisturize your hair, eliminate dandruff and rest assured of Zero Sulfate-Zero Sodium.✔️ 1\r\nHairforte Spray for germination and fall while lengthening and strengthening hair follicles.✔️ 2\r\nHereforte is an oil replacement cream to moisturize, repair & soften RK rays✔️ 3\r\n\r\n📢A routine rich in caffeine, rosemary, the most important vitamins, nutrient, moisturizing and anti-dandruff oil extracts.\r\n\r\nIt means from the first week you will see the difference and rest from dullness and dryness with frizz and breakage.\r\n\r\nAnd retrograde dense and without dandruff ✌️\r\nIf you ask for 2 packages on them a package of Valdo as a gift to solve skin problems in winter and get rid of dryness and eczema.. skin 🎁  peels and also with a rich formula for deep hydration and building the skin barrier.',
  'ingredients': [],
  'concerns': [['Dandruff']],
  'category': ['Hair Care', 'Repairing & hair moisturizing'],
  'price': '470.00',
  'product_file': None},
 {'product_id': 25,
  'name': 'Package treatment of dandruff, voids and falling (two pieces)',
  'description': 'Package treatment of dandruff, voids and falling (two pieces)\r\nEnjoy healthy and strong🌹hair without dandruff or loss with👈🏻 your Hair Fort routine with the power 📢of caffeine and rosemary with garlic oil and jojoba with moisturizing elements and anti-dandruff with the power of salicylic in two steps\r\nFirst Step:\r\nHerforte_shampoo twice weekly.\r\nNext Step:\r\nHairforte_Spray twice daily on the scalp\r\n📢And get rid of dandruff and scalp infections . And return to the health and strength of your hair without dandruff \r\nIf you ask for 2 packages on them a package of Valdo is a gift to solve the skin problems in winter and get rid of dryness and eczema.. skin peels 🎁 and also with a rich formula to deeply moisturize and build the skin barrier',
  'ingredients': [],
  'concerns': [['Hair loss']],
  'category': ['Hair Care', 'Repairing & hair moisturizing'],
  'price': '299.00',
  'product_file': None}]

In [ ]:
@tool
def filter_products_by_category_and_concern(categories: list, concerns: list) -> List[Dict]:
    """
    Filter products by both categories and concerns.
    
    Args:
        categories (list): List of product categories to filter by (e.g., ['Hair Care', 'Shampoos'])
        concerns (list): List of health/beauty concerns to filter by (e.g., ['Hair loss', 'Dandruff'])
    
    Returns:
        List[Dict]: A list of products matching both the specified categories and concerns
    """
    # Filter by categories
    category_matches = df[df['category'].apply(
        lambda x: any(cat.lower() in c.lower() for cat in categories for c in x)
    )]
    
    # Further filter by concerns
    matches = category_matches[category_matches['concerns'].apply(
        lambda x: any(con.lower() in c[0].lower() for con in concerns for c in x if c)
    )]
    
    return matches.to_dict('records')

In [9]:
from typing import List, Dict, Optional
from langchain_core.tools import tool
import pandas as pd

# Assuming your DataFrame is loaded as df
# df = pd.read_csv('your_products.csv')

@tool
def search_products_by_concern(concern: str) -> List[Dict]:
    """
    Search for products by health/beauty concern (e.g., 'Hair loss', 'Dandruff', 'Eczema').
    
    Args:
        concern (str): The health or beauty concern to search for
    
    Returns:
        List[Dict]: A list of products addressing the specified concern
    """
    matches = df[df['concerns'].apply(
        lambda x: any(concern.lower() in c[0].lower() for c in x if c)
    )]
    return matches.to_dict('records')

@tool
def search_products_by_category(category: str) -> List[Dict]:
    """
    Search for products by category (e.g., 'Hair Care', 'Skin Care').
    
    Args:
        category (str): The category to search for
    
    Returns:
        List[Dict]: A list of products in the specified category
    """
    matches = df[df['category'].apply(
        lambda x: any(category.lower() in c.lower() for c in x)
    )]
    return matches.to_dict('records')

@tool
def search_products_by_name(name: str) -> List[Dict]:
    """
    Search for products by name.
    
    Args:
        name (str): The product name to search for (partial matches allowed)
    
    Returns:
        List[Dict]: A list of products matching the name query
    """
    matches = df[df['name'].str.lower().str.contains(name.lower())]
    return matches.to_dict('records')

@tool
def get_lowest_price_products(n: int = 5) -> List[Dict]:
    """
    Get the lowest priced products.
    
    Args:
        n (int): Number of products to return
    
    Returns:
        List[Dict]: A list of the n lowest priced products
    """
    return df.nsmallest(n, 'price').to_dict('records')

@tool
def get_highest_price_products(n: int = 5) -> List[Dict]:
    """
    Get the highest priced products.
    
    Args:
        n (int): Number of products to return
    
    Returns:
        List[Dict]: A list of the n highest priced products
    """
    return df.nlargest(n, 'price').to_dict('records')

@tool
def get_products_in_price_range(min_price: float, max_price: float) -> List[Dict]:
    """
    Get products within a specific price range.
    
    Args:
        min_price (float): Minimum price
        max_price (float): Maximum price
    
    Returns:
        List[Dict]: List of products within the specified price range
    """
    matches = df[(df['price'] >= min_price) & (df['price'] <= max_price)]
    return matches.to_dict('records')

# List of tools to be used with LangGraph
tools = [
    search_products_by_concern,
    search_products_by_category,
    search_products_by_name,
    get_lowest_price_products,
    get_highest_price_products,
    get_products_in_price_range
]

In [ ]:
search_products_by_concern()